<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Categoryname' => 'Название категории',
    'About' => 'О пользователе',
    'Adress' => 'Адрес',
    'Category Idcategory' => 'Категория',
    'Categorydescription' => 'Описание категории',
    'Date' => 'Дата',
    'Dateadd' => 'Дата добавления',
    'Datereg' => 'Дата редактирования',
    'Description' => 'Описание документа',
    'Doc File' => 'Документ (файл)',
    'Doclink' => 'Документ (по ссылке)',
    'Firstname' => 'Имя',
    'Hpassword' => 'Пароль',
    'Idcategory' => 'Категория',
    'Identrhistory' => 'Лог',
    'Idimage' => 'Идентификтор изображения',
    'Iduser' => 'Идентификтор пользователя',
    'Iduserdetail' => 'Идентификатор подробности',
    'Idusersoclogin' => 'Идентификатор пользователя соцсети',
    'Info' => 'Детали о пользователе',
    'Name' => 'Название документа',
    'Phone' => 'Номер телефона',
    'Secondname' => 'Отчество',
    'Socialnet' => 'Социальная сеть',
    'Socident' => 'Идентификатор соцсети',
    'User Iduser' => 'Пользователь',
    'Userlogin' => 'Логин пользователя',
    'Username' => 'Имя пользователя',
    'Usersecondname' => 'Фамилия пользователя',
];
