<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Categories' => 'Категории',
    'Are you sure you want to delete this item?' => 'Вы действительно хотите удалить эту запись?',
    'Create Category' => 'Добавить категорию',
    'Create Photo Doc' => 'Добавить документ',
    'Create User Customer' => 'Добавить пользователя',
    'Create Userdetail' => 'Добавить данные о пользователе',
    'Delete' => 'Удалить',
    'Photo Docs' => 'Документ',
    'Save' => 'Сохранить',
    'The requested page does not exist.' => 'Запрашиваемая страница не найдена',
    'Update' => 'Изменить',
    'Update Category: {name}' => 'Изменить категорию: {name}',
    'Update Photo Doc: {name}' => 'Изменить данные документа: {name}',
    'Update User Customer: {name}' => 'Изменить данные пользователя: {name}',
    'Update Userdetail: {name}' => 'Изменить данные о пользователе: {name}',
    'User Customers' => 'Пользователь',
    'Userdetails' => 'Данные пользователя',
    'UploadDoc' => 'Загрузить документ',
    'Back' => 'Назад',
    'imageFile' => 'Загрузить документ'


];
